name: appsoed
description: A new Flutter project.

publish_to: "none"

version: 2.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.2.1
  cupertino_icons: ^1.0.5
  file_picker: ^4.6.1
  firebase_core: ^1.19.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.9
  font_awesome_flutter: ^10.1.0
  get: ^4.6.5
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  http: ^0.13.5
  intl: ^0.17.0
  provider: ^6.0.3
  responsive_framework: ^0.2.0
dev_dependencies:
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.1.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appsoed-logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/data/
    - assets/lokasi/
    - assets/galeri/
