name: appsoed
description: A new Flutter project.

publish_to: "none"

version: 2.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.2.1
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.5
  firebase_core: ^1.19.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.9
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.6.0
  path_provider: ^2.0.11
  provider: ^6.0.3
  responsive_framework: ^0.2.0
  sqflite: ^2.0.3+1
  url_launcher: ^6.1.5
  webview_flutter: ^3.0.4
dev_dependencies:
  build_runner: ^2.2.0
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/Poppins-Regular.ttf

flutter_native_splash:
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # flutter pub run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # flutter pub run flutter_native_splash:remove

  # color or background_image is the only required parameter.  Use color to set the background
  # of your splash screen to a solid color.  Use background_image to set the background of your
  # splash screen to a png image.  This is useful for gradients. The image will be stretch to the
  # size of the app. Only one parameter can be used, color and background_image cannot both be set.
  color: "#FFFFFF"
  #background_image: "assets/background.png"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

  # The image parameter allows you to specify an image used in the splash screen.  It must be a
  # png file and should be sized for 4x pixel density.
  image: assets/logo.png
